// Date: 04/03/2018 02:12:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;


public class ModelScythe extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
  
  public ModelScythe()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 8, 20, 8);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 42, 8);
      Shape2.addBox(0F, 0F, 0F, 6, 13, 6);
      Shape2.setRotationPoint(1F, -13F, 0F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 70, 0);
      Shape3.addBox(0F, 0F, 0F, 4, 10, 4);
      Shape3.setRotationPoint(2F, -23F, 0F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 89, 8);
      Shape4.addBox(0F, 0F, 0F, 6, 13, 6);
      Shape4.setRotationPoint(1F, -36F, 1F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 8, 17, 8);
      Shape5.setRotationPoint(0F, -53F, 0F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 29);
      Shape6.addBox(0F, 0F, 0F, 4, 2, 10);
      Shape6.setRotationPoint(2F, -4F, 6F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 68, 17);
      Shape7.addBox(0F, 0F, 0F, 4, 7, 2);
      Shape7.setRotationPoint(2F, -11F, 14F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 33, 29);
      Shape8.addBox(0F, 0F, 0F, 4, 2, 10);
      Shape8.setRotationPoint(2F, -31F, 7F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 10, 45);
      Shape9.addBox(0F, 0F, 0F, 8, 6, 14);
      Shape9.setRotationPoint(0F, -59F, 0F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 68, 29);
      Shape10.addBox(0F, 0F, 0F, 8, 4, 8);
      Shape10.setRotationPoint(0F, -63F, 0F);
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 10, 67);
      Shape11.addBox(0F, 0F, 0F, 8, 9, 16);
      Shape11.setRotationPoint(0F, -61F, 14F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, -0.0895385F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 17, 101);
      Shape12.addBox(0F, 0F, 0F, 8, 7, 14);
      Shape12.setRotationPoint(0F, -59F, 30F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, -0.3239703F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 63, 54);
      Shape13.addBox(0F, 0F, 0F, 8, 6, 9);
      Shape13.setRotationPoint(0F, -54F, 43F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, -0.7982041F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 63, 73);
      Shape14.addBox(0F, 0F, 0F, 4, 4, 6);
      Shape14.setRotationPoint(2F, -47F, 49F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, -0.90974F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
